### ISSUE TITLE
cant open Liroth Splitter

### ISSUE THREAD

**Issue by WindEssence** [decodinatorX/Liroth-Revamped-Forge#2]
[latest.log](https://github.com/decodinatorX/Liroth-Revamped-Forge/files/9822103/latest.log)

**Comment by decodinatorX** [comment]
One of your mods seems to be having conflict with most of the mods in the pack, I've noticed that multiple biome tags are just not loaded due to an overarching issue of one possibly not loading correctly. I couldn't properly assess what was causing the Liroth Splitter to fail due to the amount of bloat that takes up the current modpack, my advice is try using it on a clean modpack alone and see if it opens for you, if it does, then there is another mod in the modpack causing issues.
